/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ContributorsPleaseConfig {
  classifier?: "path";
  classification?: Classification;
  identity_map?: {
    login: string;
    emails: string[];
  }[];
  no_reply_domain?: string;
  packages?: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
  [k: string]: unknown;
}
export interface Classification {
  categories: Category[];
  default: DefaultCategory;
  combinations?: Combination[];
  multi_category_resolution?: "priority" | "combine";
}
export interface Category {
  id: string;
  label: string;
  emoji?: string;
  /**
   * @minItems 1
   */
  paths: [string, ...string[]];
}
export interface DefaultCategory {
  id: string;
  label: string;
  emoji?: string;
}
export interface Combination {
  id?: string;
  label: string;
  emoji?: string;
  /**
   * @minItems 1
   */
  when: [string, ...string[]];
}
