/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ContributorsPleaseConfig {
  classifier?: "path";
  classification?: Classification;
  identity_map?: {
    login: string;
    emails: string[];
  }[];
  no_reply_domain?: string;
  output_file?: string;
  state_file?: string;
  config_file?: string;
  template_file?: string;
  template_placeholder?: string;
  header?: string;
  footer?: string;
  in_place?: boolean;
  in_place_marker_start?: string;
  in_place_marker_end?: string;
  entry_template?: string;
  empty_text?: string;
  /**
   * Number of rendered entries joined (space-separated) onto each output row. Defaults to 6. Values greater than 1 are only safe for compact, bare-token entries; an entry_template that contains a '|' delimiter, begins with a markdown list/heading marker, or contains a newline emits a warning at columns_per_row > 1 because entries concatenate onto a single row. Set columns_per_row: 1 for such templates (including the default markdown-list template).
   */
  columns_per_row?: number;
  sort?: "contributions" | "alphabetical" | "first-seen";
  min_contributions?: number;
  ignore?: string | string[];
  unignore?: string | string[];
  pin_warn_on_stale?: boolean;
  packages?: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
}
export interface Classification {
  categories: Category[];
  default: DefaultCategory;
  combinations?: Combination[];
  multi_category_resolution?: "priority" | "combine";
}
export interface Category {
  id: string;
  label: string;
  emoji?: string;
  /**
   * @minItems 1
   */
  paths: [string, ...string[]];
}
export interface DefaultCategory {
  id: string;
  label: string;
  emoji?: string;
}
export interface Combination {
  id?: string;
  label: string;
  emoji?: string;
  /**
   * @minItems 1
   */
  when: [string, ...string[]];
}
