import { describe, expect, it } from "vitest";

import { GitHubClient } from "../../src/engine/github";

describe("GitHubClient", () => {
  it("derives github.com REST and GraphQL URLs", () => {
    const urls = GitHubClient.deriveUrls("https://github.com");

    expect(urls.apiUrl).toBe("https://api.github.com");
    expect(urls.graphqlUrl).toBe("https://api.github.com/graphql");
  });

  it("derives GitHub Enterprise REST and GraphQL URLs", () => {
    const urls = GitHubClient.deriveUrls("https://github.acme.corp");

    expect(urls.apiUrl).toBe("https://github.acme.corp/api/v3");
    expect(urls.graphqlUrl).toBe("https://github.acme.corp/api/graphql");
  });

  it("maps contributors API rows to public contributor metadata", async () => {
    const seenUrls: string[] = [];
    const client = await GitHubClient.create({
      owner: "smorinlabs",
      repo: "example",
      token: "test-token",
      fetch: async (url, init) => {
        seenUrls.push(String(url));
        expect(init?.headers).toMatchObject({
          authorization: "Bearer test-token",
        });
        return new Response(
          JSON.stringify([
            {
              login: "ada",
              contributions: 3,
              avatar_url: "https://avatars/ada",
              html_url: "https://github.com/ada",
            },
          ]),
          { status: 200 }
        );
      },
    });

    await expect(client.listContributors()).resolves.toEqual([
      {
        login: "ada",
        name: "ada",
        avatar: "https://avatars/ada",
        profile: "https://github.com/ada",
        commits: 3,
      },
    ]);
    expect(seenUrls).toEqual([
      "https://api.github.com/repos/smorinlabs/example/contributors?per_page=100",
    ]);
  });

  it("follows contributors API pagination links", async () => {
    const seenUrls: string[] = [];
    const client = await GitHubClient.create({
      owner: "smorinlabs",
      repo: "example",
      fetch: async (url) => {
        seenUrls.push(String(url));
        if (String(url).endsWith("page=2")) {
          return new Response(
            JSON.stringify([
              {
                login: "grace",
                contributions: 2,
              },
            ]),
            { status: 200 }
          );
        }
        return new Response(
          JSON.stringify([
            {
              login: "ada",
              contributions: 3,
            },
          ]),
          {
            status: 200,
            headers: {
              link: '<https://api.github.com/repos/smorinlabs/example/contributors?per_page=100&page=2>; rel="next"',
            },
          }
        );
      },
    });

    await expect(client.listContributors()).resolves.toMatchObject([
      { login: "ada", commits: 3 },
      { login: "grace", commits: 2 },
    ]);
    expect(seenUrls).toEqual([
      "https://api.github.com/repos/smorinlabs/example/contributors?per_page=100",
      "https://api.github.com/repos/smorinlabs/example/contributors?per_page=100&page=2",
    ]);
  });

  it("updates an existing open pull request for the bot branch", async () => {
    const calls: Array<{ url: string; method: string; body?: unknown }> = [];
    const client = await GitHubClient.create({
      owner: "smorinlabs",
      repo: "example",
      fetch: async (url, init) => {
        calls.push({
          url: String(url),
          method: init?.method ?? "GET",
          body: init?.body ? JSON.parse(String(init.body)) : undefined,
        });
        if (String(url).includes("/pulls?")) {
          return new Response(
            JSON.stringify([
              {
                number: 12,
                html_url: "https://github.com/smorinlabs/example/pull/12",
              },
            ]),
            { status: 200 }
          );
        }
        if (String(url).endsWith("/pulls/12")) {
          return new Response(
            JSON.stringify({
              number: 12,
              html_url: "https://github.com/smorinlabs/example/pull/12",
            }),
            { status: 200 }
          );
        }
        if (String(url).endsWith("/issues/12/labels")) {
          return new Response(JSON.stringify({}), { status: 200 });
        }
        throw new Error(`unexpected request ${init?.method ?? "GET"} ${url}`);
      },
    });

    const result = await client.openPullRequest({
      head: "contributors-please/update",
      base: "main",
      title: "docs: update contributors",
      body: "Generated by contributors-please.",
      labels: ["contributors-please: pending"],
    });

    expect(result).toEqual({
      number: 12,
      url: "https://github.com/smorinlabs/example/pull/12",
    });
    expect(calls).toEqual([
      {
        url: "https://api.github.com/repos/smorinlabs/example/pulls?state=open&head=smorinlabs%3Acontributors-please%2Fupdate&base=main&per_page=1",
        method: "GET",
      },
      {
        url: "https://api.github.com/repos/smorinlabs/example/pulls/12",
        method: "PATCH",
        body: {
          base: "main",
          body: "Generated by contributors-please.",
          title: "docs: update contributors",
        },
      },
      {
        url: "https://api.github.com/repos/smorinlabs/example/issues/12/labels",
        method: "POST",
        body: { labels: ["contributors-please: pending"] },
      },
    ]);
  });

  it("does not create a label when it already exists", async () => {
    const calls: Array<{ url: string; method: string; body?: unknown }> = [];
    const client = await GitHubClient.create({
      owner: "smorinlabs",
      repo: "example",
      fetch: async (url, init) => {
        calls.push({
          url: String(url),
          method: init?.method ?? "GET",
          body: init?.body ? JSON.parse(String(init.body)) : undefined,
        });
        return new Response(JSON.stringify({ name: "contributors-please: pending" }), {
          status: 200,
        });
      },
    });

    await client.ensureLabel({
      name: "contributors-please: pending",
      color: "0E8A16",
      description: "Pull request opened by contributors-please",
    });

    expect(calls).toEqual([
      {
        url: "https://api.github.com/repos/smorinlabs/example/labels/contributors-please%3A%20pending",
        method: "GET",
      },
    ]);
  });

  it("creates the contributors-please label after a 404 lookup", async () => {
    const calls: Array<{ url: string; method: string; body?: unknown }> = [];
    const client = await GitHubClient.create({
      owner: "smorinlabs",
      repo: "example",
      fetch: async (url, init) => {
        calls.push({
          url: String(url),
          method: init?.method ?? "GET",
          body: init?.body ? JSON.parse(String(init.body)) : undefined,
        });
        if ((init?.method ?? "GET") === "GET") {
          return new Response(JSON.stringify({ message: "Not Found" }), {
            status: 404,
          });
        }
        return new Response(JSON.stringify({ name: "contributors-please: pending" }), {
          status: 201,
        });
      },
    });

    await client.ensureLabel({
      name: "contributors-please: pending",
      color: "0E8A16",
      description: "Pull request opened by contributors-please",
    });

    expect(calls).toEqual([
      {
        url: "https://api.github.com/repos/smorinlabs/example/labels/contributors-please%3A%20pending",
        method: "GET",
      },
      {
        url: "https://api.github.com/repos/smorinlabs/example/labels",
        method: "POST",
        body: {
          name: "contributors-please: pending",
          color: "0E8A16",
          description: "Pull request opened by contributors-please",
        },
      },
    ]);
  });

  it("updates an existing contributors-please issue comment in place", async () => {
    const calls: Array<{ url: string; method: string; body?: unknown }> = [];
    const client = await GitHubClient.create({
      owner: "smorinlabs",
      repo: "example",
      fetch: async (url, init) => {
        calls.push({
          url: String(url),
          method: init?.method ?? "GET",
          body: init?.body ? JSON.parse(String(init.body)) : undefined,
        });
        if (String(url).endsWith("/issues/42/comments?per_page=100")) {
          return new Response(
            JSON.stringify([
              {
                id: 1001,
                body: "<!-- contributors-please:check-comment -->\nold",
              },
            ]),
            { status: 200 }
          );
        }
        if (String(url).endsWith("/issues/comments/1001")) {
          return new Response(JSON.stringify({}), { status: 200 });
        }
        throw new Error(`unexpected request ${init?.method ?? "GET"} ${url}`);
      },
    });

    await client.upsertIssueComment(
      42,
      "<!-- contributors-please:check-comment -->\nnew"
    );

    expect(calls).toEqual([
      {
        url: "https://api.github.com/repos/smorinlabs/example/issues/42/comments?per_page=100",
        method: "GET",
      },
      {
        url: "https://api.github.com/repos/smorinlabs/example/issues/comments/1001",
        method: "PATCH",
        body: { body: "<!-- contributors-please:check-comment -->\nnew" },
      },
    ]);
  });
});
